# Config
# ========================================================================================

url: https://pushdown99.github.io
baseurl: ""
lang: en
title:                 Just-Ho-It
description:           >
  "Best Jekyll Theme by a Mile".
tagline:  '"Best Jekyll Theme by a Mile"'
keywords: []
logo: /assets/icons/icon.png
author:
  name: haeyeon hwang
  email: haeyun@gmail.com
copyright: >
  © 2018. All rights reserved.

permalink: /:categories/:year-:month-:day-:title/
paginate: 5
paginate_path: /page-:num/

accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)

theme_color: rgb(25,55,71)

google_fonts: 'Roboto+Slab:400|Noto+Sans:400,400i,700,700i'
font: Roboto Slab, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif

defaults:
  - scope:
      path: hyde
    values:
      accent_color: rgb(38,139,210)
      accent_image:
        background: rgb(32,32,32)
        overlay: false

  - scope:
      type: projects
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_categories
    values:
      seo:
        type: WebPage
  - scope:
      type: featured_tags
    values:
      seo:
        type: WebPage

hydejack:
  post_addons: [about, newsletter, related]
  project_addons: [about, newsletter, other]
  no_google_fonts: false
  no_mark_external: true
  no_push_state: false
  no_drawer: false
  no_img: false
  no_inline_css: false
  no_break_layout: false
  no_structured_data: false
  no_theme_color: false
  use_lsi: false
  cookies_banner: false
  advertise: false
  dark_mode:
    always: false
    dynamic: true
    sunrise: 6
    sunset: 18
    icon: true
  offline:
    enabled: false
    cache_version: 1

collections:
  featured_categories:
    permalink: /:name/
    output: true

  featured_tags:
    permalink: /tag-:name/
    output: true

  projects:
    permalink: /projects/:path/
    output: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.gemspec"
  - _js
  - _plugins
  - .sass-cache
include:
  - LICENSE.md

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-algolia

blame: https://github.com/pushdown99/pushdown99.github.io/blame/master/_wiki 

# Other Plugins
# ---------------------------------------------------------------------------------------

optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all
  ignore:
    envs: [development]

sass:
  style: compressed

algolia:
  application_id: ULCVVAH9L3
  index_name:     wb9lab 
  search_only_api_key: b7a2397d9e29ab1fc96d6e0f2ea5eae9
  files_to_exclude: 
    - index.html
    - index.md
